# Generated by Django 3.2.6 on 2021-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210903_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
