# Generated by Django 3.2.6 on 2021-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_spell_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='higher_level',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='level',
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
